import Head from 'next/head';
import { useState } from "react";
import {CgMenuRightAlt} from "react-icons/cg"
import {FaTimes} from "react-icons/fa"
import {Link} from "react-scroll";
import logo from '../public/logo.png';
import net from '../public/net.png';
import germs from '../public/germs.png';
import treats from '../public/treats.png';
import tools from '../public/tools.png';
import Image from 'next/image';
import L2R from '../public/L2R.png';



export default function Home() {
  const [nav, setNav] = useState(false);
  const links = [
    {
      id: 1,
      link:"Contact"
    },
    {
      id: 2,
      link:"Our App"
    },
    {
      id: 3,
      link:"Price"
    },
    {
      id: 4,
      link:"Services"
    },
    {
      id: 5,
      link:"About Us"
    },
    {
      id: 6,
      link:"Home"
    },
  ];

  return (
   
    <div>
      <Head>
        <title>Old Guys Pool Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div className=' px-4 flex justify-between items-center w-full h-20 fixed bg-blue-500 opacity-90 z-10 '>
           
           
         
           

            <ul className='gap-10 hidden lg:flex'>
                {links.map(({id,link}) => (
                <li key={id} className='text-2xl cursor-pointer text-white hover:scale-110 duration-200 '>
                 <Link to={link} smooth duration={500}>{link}</Link>
                </li>

                ))}
            </ul>
            <div onClick={()=> setNav(!nav)} className='cursor-pointer pr-4 z-10 text-white lg:hidden hover:scale-110 duration-200 '>
                { nav ? <FaTimes size={60} /> : <CgMenuRightAlt size={60} /> }
          </div>

            { nav && (
                <ul className='gap-20 flex flex-col justify-center items-center absolute top-0 left-0 w-full h-screen bg-amber-700 z-10'>
                    {links.map(({id,link}) => (
                <li key={id} className='text-5xl cursor-pointer hover:scale-110 duration-200 hover:text-neutral-500 text-white hover:text-blue-400 '>
                 <Link onClick= {()=>setNav(!nav)}to={link}  smooth duration={500} >{link}</Link>
                </li>

                ))}
                </ul>
                      )}         
       </div>


       {/*
       end of nav bar--------------------------------------------------------------
       */}


 <div name='Home' className='h-screen w-full bg-white'>
              <div className='max-w-screen-1xl mx-auto flex flex-col items-center gap-20 justify-center h-full px-4 md:flex-row'>
                <div>
                <div className='pb-10'>
                  <Image src={logo} id='logo' className='mx-auto w-2/3 rounded-2xl md:w-2/3 max-w-lg border-solid border-8 border-blue-400 rounded-full' />
                </div>

                <div className='flex flex-col justify-center h-full sm:h-2/5'>
                  <h2 className='xl:text-9xl lg:text-7xl sm:text-7xl font-bold text-amber-600 mx-auto text-center'> Old Guys <br /> Pool Service</h2>
                </div>
                <div className='text-center pt-20'>
                <a href="tel:925-437-1526" className='text-amber-600 text-2xl border-solid border-4 border-blue-500 rounded-lg p-5 hover:scale-105 duration-200 '>Give us a call</a>
                </div>
                </div>

              </div>
              <section>
                <div className='wave wave1'></div>
                <div className='wave wave2'></div>
                <div className='wave wave3'></div>
                <div className='wave wave4'></div>
              </section>

            </div>


       {/*
       end of homepage --------------------------------------------------------------
       */}

<div name='About Us' className='h-screen w-full '>
          <div className='max-w-screen-2xl p-4 mx-auto flex flex-col justify-center w-full h-full '>
                <div className='pb-8'>
                    <p className='text-7xl text-amber-600 font-bold inline border-b-4 border-blue-400'>About US</p>  
                </div>
              
                   <p className='leading-20 xl:text-5xl text-amber-600 mt-10 md:text-3xl md:mx-6 sm:text-2xl sm:mx-10' id='para'> Here at Old Guys Pool Service (OGPS) we dont understand the word "retirement".
                            We are a family owned and operated buisness dedicated in helping people with their pool service needs in the East Bay Area all year round for a flat and affordable price.                
                                              </p>   
                                              <p className='leading-20 xl:text-5xl text-amber-600 mt-10 md:text-3xl md:mx-6 sm:text-2xl sm:mx-10' id='para'> We understand times are hard, maintaining a clean and functioning
                                              pool is very challenging, overwhelming and EXPENSIVE. Thats why we take our customers needs seriously, and have made it our mission to be the ones ANYONE can turn to without going broke.
                                               </p>  
            
          </div>
         
</div>

 {/*
       end of about us --------------------------------------------------------------
       */}

<div name='Services' className='h-screen w-full bg-white'>
              <div className='max-w-screen-1xl mx-auto flex flex-col items-center gap-20 justify-center h-full px-4 md:flex-row'>
                <div>
              

                <div className='xl:pb-20 flex flex-col justify-center h-full sm:h-1/5 sm:pb-20 '>
                  <h2 className='xl:text-9xl lg:text-7xl sm:text-7xl font-bold text-amber-600 mx-auto text-center'> Our Services <br /> To You</h2>
                </div>

               
              <div className=' grid sm:grid-cols-2 max-screen-md grid-cols-2 gap-10 px-12 sm:px-0 pb-20'>

<div className='  shadow-md shadow-orange-500 rounded-xl hover:scale-105 duration-200 dark:shadow-blue-300'>
  <Image src={net} className='rounded-md duration-200 mx-auto pt-5'/>
  <div className='flex items-center justify-center '>
    <h1 className='w-1/2 px-6 py-3 m-4 text-2xl duration-200 hover:scale-105 md:text-lg text-amber-600 text-center sm:text-lg'>Filter cleaning and replaceing</h1>
    
  </div>
</div>

<div className=' shadow-md shadow-orange-500 rounded-xl duration-200 hover:scale-105 dark:shadow-blue-300'>
  <Image src={germs} className='rounded-md mx-auto pt-5'/>
  <div className='flex items-center justify-center'>
    <h1 className='w-1/2 px-6 py-3 m-4 text-2xl duration-200 hover:scale-105 md:text-lg text-amber-600 text-center sm:text-lg'>replenish of all chemicals </h1>
    
  </div>
</div> 

<div className=' shadow-md shadow-orange-500 rounded-xl hover:scale-105 duration-200 dark:shadow-blue-300'>
  <Image src={tools} className='rounded-md duration-200 mx-auto'/>
  <div className='flex items-center justify-center pt-5'>
    <h1 className='w-1/2 px-6 py-3 m-4 text-2xl duration-200 hover:scale-105 md:text-lg text-amber-600 text-center sm:text-lg'>Full clean up: In, above & around pool area</h1>
    
  </div>
</div>

<div className=' shadow-md shadow-orange-500 rounded-xl duration-200 hover:scale-105 dark:shadow-blue-300'>
  <Image src={treats} className='rounded-md mx-auto pt-5'/>
  <div className='flex items-center justify-center'>
    <h1 className='w-1/2 px-6 py-3 m-4 text-2xl duration-200 hover:scale-105 md:text-lg text-amber-600 text-center sm:text-lg'>We bring treats for your fur babies</h1>
    
  </div>
</div>

</div>
                </div>

              </div>
                
            </div>



 {/*
       end of services --------------------------------------------------------------
       */}

            <div name='Price' className='h-screen w-full bg-white'>
              <div className='max-w-screen-1xl mx-auto flex flex-col items-center gap-20 justify-center h-full px-4 md:flex-row'>
                <div>
    
                <div className='flex flex-col pb-20 justify-center h-full sm:h-2/5'>
                  <h2 className='xl:text-9xl lg:text-7xl sm:text-7xl font-bold text-amber-600 mx-auto text-center inline pb-5 border-b-4 border-blue-400'> $70 a month <br /> FLAT!</h2>
                </div>

                <div className=''>
                <ul className='xl:text-6xl lg:text-6xl sm:text-4xl font-bold text-blue-300 mx-auto text-center'> 
                <li className='pb-5'>No fees. </li>  
                <li className='pb-5'>No sur charge.</li> 
                <li>No BS, we're to old for that. </li>  
                </ul>
                </div>

                </div>

              </div>
            
            </div>

 {/*
       end of prices --------------------------------------------------------------
       */}

<div name="Our App" className='h-screen w-full bg-white'>
              <div className='max-w-screen-1xl mx-auto flex flex-col items-center justify-center h-full px-4 flex-row'>
              
                <div className='flex flex-col justify-center h-full xl:h-2/5 sm:h-1/4'>

                  <h2 className='xl:text-8xl  sm:text-5xl font-bold text-amber-600 py-5 inline border-b-4 border-blue-400'>Our App Includes </h2>
                     <div className=''>
                     <ul className=' xl:text-5xl text-blue-400 mt-10 sm:text-3xl'>  
                     <li className='pb-5'>Updates on next cleaning.</li>
                     <li className='pb-5'>24/7 Reachability.</li>
                     <li className='pb-5'>Pay your bill on the app.</li>
                     <li className='pb-5'>Before and after posts of your pool.</li>
                     </ul>  
                     </div>
                </div>
                <div className=' '>
                  <Image src={L2R} className='mx-auto w-2/3 rounded-2xl md:w-full max-w-lg sm:w-full' />
                 
                  <p className='text-amber-600 text-center xl:text-3xl sm:text-xl'>Get the app free from the App-store today!</p>
                </div>
              </div>
              
            </div>


 {/*
       end of app --------------------------------------------------------------
       */}


                  <div name='Contact' className='h-screen w-full '>
                  <div className='flex flex-col p-4 justify-center max-w-screen-lg mx-auto h-full'>
                              <div className='pb-8 '>
                                <p className='text-7xl font-bold inline border-b-4 border-blue-500 text-amber-600'>Contact Us</p>
                                <div className='pt-6'>
                                <p className='py-6 xl:text-3xl text-amber-600 sm:text-xl'> Reach out to us, well get back to you soon! </p>
                                </div>
                              </div>
                              <div className='flex justify-center items-center'>
                                <form action='https://getform.io/f/c73b689e-c58f-4644-877c-e2c79096ae99' method='POST' className=' flex flex-col w-full md:w-1/2'>
                                  <input type="text" name='Name' placeholder='Enter your name'className='p-2 bg-transparent border-4 border-blue-300 rounded-md text-amber-600 focus:outline-none' />
                                  <input type="text" name='Email' placeholder='Enter your Email'className=' my-4 p-2 bg-transparent border-4 border-blue-300 rounded-md text-amber-600 focus:outline-none' />
                                  <textarea name="Message" rows="10" placeholder='Enter your message' className='p-2 bg-transparent border-4 border-blue-300 rounded-md text-amber-600 focus:outline-none'>
                                  </textarea>
                                  <button className='text-amber-600 bg-transparent border-4 border-blue-300 rounded-md my-8 py-2 px-3 mx-auto flex items-center hover:scale-110 duration-200'>Send</button>
                                </form>
                              </div>
                            
                      </div>
                    
          
                  </div>




</div>
     
  )
}



